//------------------------------------------------------------------------------
// <auto-generated>
//     生成済みコード - resx 編集後に再生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisfactorySaveEditor.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Workflow", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public static class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager("SatisfactorySaveEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string MenuFile => ResourceManager.GetString("MenuFile", resourceCulture);
        public static string MenuOpen => ResourceManager.GetString("MenuOpen", resourceCulture);
        public static string MenuOpenRecent => ResourceManager.GetString("MenuOpenRecent", resourceCulture);
        public static string MenuSave => ResourceManager.GetString("MenuSave", resourceCulture);
        public static string MenuSaveAs => ResourceManager.GetString("MenuSaveAs", resourceCulture);
        public static string MenuCreateBackup => ResourceManager.GetString("MenuCreateBackup", resourceCulture);
        public static string MenuJumpToTag => ResourceManager.GetString("MenuJumpToTag", resourceCulture);
        public static string MenuPreferences => ResourceManager.GetString("MenuPreferences", resourceCulture);
        public static string MenuExit => ResourceManager.GetString("MenuExit", resourceCulture);
        public static string MenuCheats => ResourceManager.GetString("MenuCheats", resourceCulture);
        public static string MenuHelp => ResourceManager.GetString("MenuHelp", resourceCulture);
        public static string Menu3DView => ResourceManager.GetString("Menu3DView", resourceCulture);
        public static string MsgCheatUnsupportedV2_Title => ResourceManager.GetString("MsgCheatUnsupportedV2_Title", resourceCulture);
        public static string MsgCheatUnsupportedV2_Body => ResourceManager.GetString("MsgCheatUnsupportedV2_Body", resourceCulture);
        public static string Msg3DNoSave_Body => ResourceManager.GetString("Msg3DNoSave_Body", resourceCulture);
        public static string MenuViewGuidesFicsit => ResourceManager.GetString("MenuViewGuidesFicsit", resourceCulture);
        public static string MenuRequestHelpDiscord => ResourceManager.GetString("MenuRequestHelpDiscord", resourceCulture);
        public static string MenuViewOnGitHub => ResourceManager.GetString("MenuViewOnGitHub", resourceCulture);
        public static string MenuReportIssue => ResourceManager.GetString("MenuReportIssue", resourceCulture);
        public static string MenuCheckForUpdates => ResourceManager.GetString("MenuCheckForUpdates", resourceCulture);
        public static string MenuAbout => ResourceManager.GetString("MenuAbout", resourceCulture);
        public static string MainSearchPlaceholder => ResourceManager.GetString("MainSearchPlaceholder", resourceCulture);
        public static string MainSearchClearTooltip => ResourceManager.GetString("MainSearchClearTooltip", resourceCulture);
        public static string CommonCopyName => ResourceManager.GetString("CommonCopyName", resourceCulture);
        public static string CommonCopyPath => ResourceManager.GetString("CommonCopyPath", resourceCulture);
        public static string CommonFillInventory => ResourceManager.GetString("CommonFillInventory", resourceCulture);
        public static string CommonEmptyInventory => ResourceManager.GetString("CommonEmptyInventory", resourceCulture);
        public static string CommonDelete => ResourceManager.GetString("CommonDelete", resourceCulture);
        public static string CommonAdd => ResourceManager.GetString("CommonAdd", resourceCulture);
        public static string CommonEntity => ResourceManager.GetString("CommonEntity", resourceCulture);
        public static string CommonComponent => ResourceManager.GetString("CommonComponent", resourceCulture);
        public static string MainEntityHeader => ResourceManager.GetString("MainEntityHeader", resourceCulture);
        public static string MainEntityName => ResourceManager.GetString("MainEntityName", resourceCulture);
        public static string CommonRoot => ResourceManager.GetString("CommonRoot", resourceCulture);
        public static string MainNeedTransform => ResourceManager.GetString("MainNeedTransform", resourceCulture);
        public static string MainWasPlacedInLevel => ResourceManager.GetString("MainWasPlacedInLevel", resourceCulture);
        public static string MainPosition => ResourceManager.GetString("MainPosition", resourceCulture);
        public static string MainRotation => ResourceManager.GetString("MainRotation", resourceCulture);
        public static string MainScale => ResourceManager.GetString("MainScale", resourceCulture);
        public static string MainParentObjectName => ResourceManager.GetString("MainParentObjectName", resourceCulture);
        public static string MainParentObjectRoot => ResourceManager.GetString("MainParentObjectRoot", resourceCulture);
        public static string MainComponentHeader => ResourceManager.GetString("MainComponentHeader", resourceCulture);
        public static string MainComponentName => ResourceManager.GetString("MainComponentName", resourceCulture);
        public static string MainParentEntityName => ResourceManager.GetString("MainParentEntityName", resourceCulture);
        public static string MainSaveMetadataTitle => ResourceManager.GetString("MainSaveMetadataTitle", resourceCulture);
        public static string MainSaveMetadataSubtitle => ResourceManager.GetString("MainSaveMetadataSubtitle", resourceCulture);
        public static string MainHeaderVersion => ResourceManager.GetString("MainHeaderVersion", resourceCulture);
        public static string MainSaveVersion => ResourceManager.GetString("MainSaveVersion", resourceCulture);
        public static string MainBuildVersion => ResourceManager.GetString("MainBuildVersion", resourceCulture);
        public static string MainMapName => ResourceManager.GetString("MainMapName", resourceCulture);
        public static string MainMapOptions => ResourceManager.GetString("MainMapOptions", resourceCulture);
        public static string MainSessionName => ResourceManager.GetString("MainSessionName", resourceCulture);
        public static string MainSessionVisibility => ResourceManager.GetString("MainSessionVisibility", resourceCulture);
        public static string MainSaveCreationTime => ResourceManager.GetString("MainSaveCreationTime", resourceCulture);
        public static string MainPlayDuration => ResourceManager.GetString("MainPlayDuration", resourceCulture);
        public static string CommonPleaseWait => ResourceManager.GetString("CommonPleaseWait", resourceCulture);
        public static string MainLoadingSaveFile => ResourceManager.GetString("MainLoadingSaveFile", resourceCulture);
        public static string PrefsTitle => ResourceManager.GetString("PrefsTitle", resourceCulture);
        public static string PrefsSubtitle => ResourceManager.GetString("PrefsSubtitle", resourceCulture);
        public static string PrefsGeneralHeader => ResourceManager.GetString("PrefsGeneralHeader", resourceCulture);
        public static string PrefsCheckUpdatesOnLaunch => ResourceManager.GetString("PrefsCheckUpdatesOnLaunch", resourceCulture);
        public static string PrefsCheckUpdatesOnLaunchDesc => ResourceManager.GetString("PrefsCheckUpdatesOnLaunchDesc", resourceCulture);
        public static string PrefsBackupBeforeWriting => ResourceManager.GetString("PrefsBackupBeforeWriting", resourceCulture);
        public static string PrefsBackupDesc => ResourceManager.GetString("PrefsBackupDesc", resourceCulture);
        public static string PrefsLanguageHeader => ResourceManager.GetString("PrefsLanguageHeader", resourceCulture);
        public static string PrefsLanguageDesc => ResourceManager.GetString("PrefsLanguageDesc", resourceCulture);
        public static string ButtonCancel => ResourceManager.GetString("ButtonCancel", resourceCulture);
        public static string ButtonApply => ResourceManager.GetString("ButtonApply", resourceCulture);
        public static string ButtonOK => ResourceManager.GetString("ButtonOK", resourceCulture);
        public static string AddWindowTitle => ResourceManager.GetString("AddWindowTitle", resourceCulture);
        public static string AddWindowHeader => ResourceManager.GetString("AddWindowHeader", resourceCulture);
        public static string AddWindowSubtitle => ResourceManager.GetString("AddWindowSubtitle", resourceCulture);
        public static string AddWindowType => ResourceManager.GetString("AddWindowType", resourceCulture);
        public static string AddWindowArrayElementType => ResourceManager.GetString("AddWindowArrayElementType", resourceCulture);
        public static string CommonName => ResourceManager.GetString("CommonName", resourceCulture);
        public static string FillWindowTitle => ResourceManager.GetString("FillWindowTitle", resourceCulture);
        public static string FillWindowHeader => ResourceManager.GetString("FillWindowHeader", resourceCulture);
        public static string FillWindowSubtitle => ResourceManager.GetString("FillWindowSubtitle", resourceCulture);
        public static string FillWindowItemType => ResourceManager.GetString("FillWindowItemType", resourceCulture);
        public static string FillWindowQuantityPerStack => ResourceManager.GetString("FillWindowQuantityPerStack", resourceCulture);
        public static string ButtonFill => ResourceManager.GetString("ButtonFill", resourceCulture);
        public static string CommonValue => ResourceManager.GetString("CommonValue", resourceCulture);
        public static string UpdateWindowTitle => ResourceManager.GetString("UpdateWindowTitle", resourceCulture);
        public static string UpdateWindowHeader => ResourceManager.GetString("UpdateWindowHeader", resourceCulture);
        public static string UpdateWindowSubtitle => ResourceManager.GetString("UpdateWindowSubtitle", resourceCulture);
        public static string ButtonDisableAutoCheck => ResourceManager.GetString("ButtonDisableAutoCheck", resourceCulture);
        public static string ButtonRemindLater => ResourceManager.GetString("ButtonRemindLater", resourceCulture);
        public static string ButtonOpenReleasePage => ResourceManager.GetString("ButtonOpenReleasePage", resourceCulture);
        public static string CheatInventoryTitle => ResourceManager.GetString("CheatInventoryTitle", resourceCulture);
        public static string CheatInventoryHeader => ResourceManager.GetString("CheatInventoryHeader", resourceCulture);
        public static string CheatInventoryCurrentlyPrefix => ResourceManager.GetString("CheatInventoryCurrentlyPrefix", resourceCulture);
        public static string CheatInventorySlotsSuffix => ResourceManager.GetString("CheatInventorySlotsSuffix", resourceCulture);
        public static string CheatInventoryNewCount => ResourceManager.GetString("CheatInventoryNewCount", resourceCulture);
        public static string UnlockResearchTitle => ResourceManager.GetString("UnlockResearchTitle", resourceCulture);
        public static string UnlockResearchHeader => ResourceManager.GetString("UnlockResearchHeader", resourceCulture);
        public static string UnlockResearchSubtitle => ResourceManager.GetString("UnlockResearchSubtitle", resourceCulture);
        public static string UnlockResearchAvailable => ResourceManager.GetString("UnlockResearchAvailable", resourceCulture);
        public static string UnlockResearchUnlock => ResourceManager.GetString("UnlockResearchUnlock", resourceCulture);
        public static string UnlockResearchRemove => ResourceManager.GetString("UnlockResearchRemove", resourceCulture);
        public static string UnlockResearchUnlockAll => ResourceManager.GetString("UnlockResearchUnlockAll", resourceCulture);
        public static string UnlockResearchRemoveAll => ResourceManager.GetString("UnlockResearchRemoveAll", resourceCulture);
        public static string UnlockResearchUnlockAllAlternatives => ResourceManager.GetString("UnlockResearchUnlockAllAlternatives", resourceCulture);
        public static string UnlockResearchUnlocked => ResourceManager.GetString("UnlockResearchUnlocked", resourceCulture);
        public static string ButtonCancelAccel => ResourceManager.GetString("ButtonCancelAccel", resourceCulture);
        public static string ButtonDone => ResourceManager.GetString("ButtonDone", resourceCulture);
        public static string MassDismantleTitle => ResourceManager.GetString("MassDismantleTitle", resourceCulture);
        public static string MassDismantleSubtitle => ResourceManager.GetString("MassDismantleSubtitle", resourceCulture);
        public static string MassDismantleXCoord => ResourceManager.GetString("MassDismantleXCoord", resourceCulture);
        public static string MassDismantleYCoord => ResourceManager.GetString("MassDismantleYCoord", resourceCulture);
        public static string ButtonNextPoint => ResourceManager.GetString("ButtonNextPoint", resourceCulture);
        public static string PropertiesTitle => ResourceManager.GetString("PropertiesTitle", resourceCulture);
        public static string PropertiesSubtitle => ResourceManager.GetString("PropertiesSubtitle", resourceCulture);
        public static string ButtonAddProperty => ResourceManager.GetString("ButtonAddProperty", resourceCulture);
        public static string MsgAlreadyLatestVersion_Body => ResourceManager.GetString("MsgAlreadyLatestVersion_Body", resourceCulture);
        public static string MsgUpdate_Title => ResourceManager.GetString("MsgUpdate_Title", resourceCulture);
        public static string FileFilterSaveGame => ResourceManager.GetString("FileFilterSaveGame", resourceCulture);
        public static string MsgBackupError_Body => ResourceManager.GetString("MsgBackupError_Body", resourceCulture);
        public static string MsgBackupCreated_Body => ResourceManager.GetString("MsgBackupCreated_Body", resourceCulture);
        public static string MsgDiscordRedirect_Body => ResourceManager.GetString("MsgDiscordRedirect_Body", resourceCulture);
        public static string MsgFicsitRedirect_Body => ResourceManager.GetString("MsgFicsitRedirect_Body", resourceCulture);
        public static string MsgAboutEditorName_Body => ResourceManager.GetString("MsgAboutEditorName_Body", resourceCulture);
        public static string MsgAbout_Title => ResourceManager.GetString("MsgAbout_Title", resourceCulture);
        public static string MsgUnsavedChangesOpen_Body => ResourceManager.GetString("MsgUnsavedChangesOpen_Body", resourceCulture);
        public static string MsgUnsavedChanges_Title => ResourceManager.GetString("MsgUnsavedChanges_Title", resourceCulture);
        public static string MsgUnsavedChangesClose_Body => ResourceManager.GetString("MsgUnsavedChangesClose_Body", resourceCulture);
        public static string PromptJumpToTag_Title => ResourceManager.GetString("PromptJumpToTag_Title", resourceCulture);
        public static string PromptJumpToTag_Caption => ResourceManager.GetString("PromptJumpToTag_Caption", resourceCulture);
        public static string PromptJumpToTag_Detail => ResourceManager.GetString("PromptJumpToTag_Detail", resourceCulture);
        public static string MsgJumpToTagFailed_Body => ResourceManager.GetString("MsgJumpToTagFailed_Body", resourceCulture);
        public static string MsgRecentFileMissing_Body => ResourceManager.GetString("MsgRecentFileMissing_Body", resourceCulture);
        public static string MsgFileNotPresent_Title => ResourceManager.GetString("MsgFileNotPresent_Title", resourceCulture);
        public static string MsgOpenFileError_Body => ResourceManager.GetString("MsgOpenFileError_Body", resourceCulture);
        public static string MsgErrorOpeningFile_Title => ResourceManager.GetString("MsgErrorOpeningFile_Title", resourceCulture);
        public static string MsgEditorName_Caption => ResourceManager.GetString("MsgEditorName_Caption", resourceCulture);
        public static string MsgAutoUpdateDisabled_Body => ResourceManager.GetString("MsgAutoUpdateDisabled_Body", resourceCulture);
        public static string PromptString_Title => ResourceManager.GetString("PromptString_Title", resourceCulture);
        public static string PromptString_Caption => ResourceManager.GetString("PromptString_Caption", resourceCulture);
        public static string PromptString_Detail => ResourceManager.GetString("PromptString_Detail", resourceCulture);
        public static string MsgInventoryEmptied_Body => ResourceManager.GetString("MsgInventoryEmptied_Body", resourceCulture);
        public static string MsgInventoryEmptied_Title => ResourceManager.GetString("MsgInventoryEmptied_Title", resourceCulture);
        public static string MsgNoUnlockSubsystem_Body => ResourceManager.GetString("MsgNoUnlockSubsystem_Body", resourceCulture);
        public static string MsgNoUnlockSubsystem_Title => ResourceManager.GetString("MsgNoUnlockSubsystem_Title", resourceCulture);
        public static string MsgArmSlotsUnchanged_Body => ResourceManager.GetString("MsgArmSlotsUnchanged_Body", resourceCulture);
        public static string MsgUnchanged_Title => ResourceManager.GetString("MsgUnchanged_Title", resourceCulture);
        public static string MsgArmSlotsSet_Body => ResourceManager.GetString("MsgArmSlotsSet_Body", resourceCulture);
        public static string MsgArmSlotsVisualWarning_Body => ResourceManager.GetString("MsgArmSlotsVisualWarning_Body", resourceCulture);
        public static string MsgSuccess_Title => ResourceManager.GetString("MsgSuccess_Title", resourceCulture);
        public static string MsgNoResourceSinkSubsystem_Body => ResourceManager.GetString("MsgNoResourceSinkSubsystem_Body", resourceCulture);
        public static string MsgNoResourceSinkSubsystem_Title => ResourceManager.GetString("MsgNoResourceSinkSubsystem_Title", resourceCulture);
        public static string PromptCoupon_Title => ResourceManager.GetString("PromptCoupon_Title", resourceCulture);
        public static string PromptCoupon_Caption => ResourceManager.GetString("PromptCoupon_Caption", resourceCulture);
        public static string PromptCoupon_Detail => ResourceManager.GetString("PromptCoupon_Detail", resourceCulture);
        public static string MsgCouponMustBePositive_Body => ResourceManager.GetString("MsgCouponMustBePositive_Body", resourceCulture);
        public static string MsgCouponUnchanged_Body => ResourceManager.GetString("MsgCouponUnchanged_Body", resourceCulture);
        public static string MsgCouponMaxExceeded_Body => ResourceManager.GetString("MsgCouponMaxExceeded_Body", resourceCulture);
        public static string MsgCouponMaxExceeded_Title => ResourceManager.GetString("MsgCouponMaxExceeded_Title", resourceCulture);
        public static string MsgCouponSet_Body => ResourceManager.GetString("MsgCouponSet_Body", resourceCulture);
        public static string MsgCouldNotParse_Body => ResourceManager.GetString("MsgCouldNotParse_Body", resourceCulture);
        public static string MsgNoCrates_Body => ResourceManager.GetString("MsgNoCrates_Body", resourceCulture);
        public static string MsgNoCrates_Title => ResourceManager.GetString("MsgNoCrates_Title", resourceCulture);
        public static string MsgNoHostPlayerSimple_Body => ResourceManager.GetString("MsgNoHostPlayerSimple_Body", resourceCulture);
        public static string MsgNoHostPlayer_Title => ResourceManager.GetString("MsgNoHostPlayer_Title", resourceCulture);
        public static string MsgCratesMoved_Body => ResourceManager.GetString("MsgCratesMoved_Body", resourceCulture);
        public static string MsgDuplicateSchematicsRemoved_Body => ResourceManager.GetString("MsgDuplicateSchematicsRemoved_Body", resourceCulture);
        public static string MsgSaveMissingSubsystem_Body => ResourceManager.GetString("MsgSaveMissingSubsystem_Body", resourceCulture);
        public static string MsgCannotFindSubsystem_Title => ResourceManager.GetString("MsgCannotFindSubsystem_Title", resourceCulture);
        public static string MsgNoHostPlayer_Body => ResourceManager.GetString("MsgNoHostPlayer_Body", resourceCulture);
        public static string MsgNoAnimals_Body => ResourceManager.GetString("MsgNoAnimals_Body", resourceCulture);
        public static string MsgNoAnimals_Title => ResourceManager.GetString("MsgNoAnimals_Title", resourceCulture);
        public static string MsgEnemiesDeleted_Body => ResourceManager.GetString("MsgEnemiesDeleted_Body", resourceCulture);
        public static string PromptEverythingBox_Title => ResourceManager.GetString("PromptEverythingBox_Title", resourceCulture);
        public static string PromptCountInteger_Caption => ResourceManager.GetString("PromptCountInteger_Caption", resourceCulture);
        public static string MsgQuantityInvalid_Body => ResourceManager.GetString("MsgQuantityInvalid_Body", resourceCulture);
        public static string MsgEverythingBoxCreated_Body => ResourceManager.GetString("MsgEverythingBoxCreated_Body", resourceCulture);
        public static string MsgEverythingBoxProcessed_Title => ResourceManager.GetString("MsgEverythingBoxProcessed_Title", resourceCulture);
        public static string MsgInventorySlotsUnchanged_Body => ResourceManager.GetString("MsgInventorySlotsUnchanged_Body", resourceCulture);
        public static string MsgInventorySlotsSet_Body => ResourceManager.GetString("MsgInventorySlotsSet_Body", resourceCulture);
        public static string MsgNoPlayer_Body => ResourceManager.GetString("MsgNoPlayer_Body", resourceCulture);
        public static string MsgNoPlayer_Title => ResourceManager.GetString("MsgNoPlayer_Title", resourceCulture);
        public static string MsgKilledPlayers_Body => ResourceManager.GetString("MsgKilledPlayers_Body", resourceCulture);
        public static string MsgMassDismantleNeed2Points_Body => ResourceManager.GetString("MsgMassDismantleNeed2Points_Body", resourceCulture);
        public static string MsgMassDismantleFailed_Title => ResourceManager.GetString("MsgMassDismantleFailed_Title", resourceCulture);
        public static string MsgMassDismantleNothing_Body => ResourceManager.GetString("MsgMassDismantleNothing_Body", resourceCulture);
        public static string MsgMassDismantle_Title => ResourceManager.GetString("MsgMassDismantle_Title", resourceCulture);
        public static string MsgMassDismantleResult_Body => ResourceManager.GetString("MsgMassDismantleResult_Body", resourceCulture);
        public static string MsgDismantled_Title => ResourceManager.GetString("MsgDismantled_Title", resourceCulture);
        public static string MassDismantleMinZ_Caption => ResourceManager.GetString("MassDismantleMinZ_Caption", resourceCulture);
        public static string MassDismantleMaxZ_Caption => ResourceManager.GetString("MassDismantleMaxZ_Caption", resourceCulture);
        public static string MsgEnterCoordinates_Title => ResourceManager.GetString("MsgEnterCoordinates_Title", resourceCulture);
        public static string MsgCoordinateFormat_Body => ResourceManager.GetString("MsgCoordinateFormat_Body", resourceCulture);
        public static string MsgNoGameState_Body => ResourceManager.GetString("MsgNoGameState_Body", resourceCulture);
        public static string MsgNoGameState_Title => ResourceManager.GetString("MsgNoGameState_Title", resourceCulture);
        public static string MsgNoCostEnabled_Body => ResourceManager.GetString("MsgNoCostEnabled_Body", resourceCulture);
        public static string MsgNoCostDisabled_Body => ResourceManager.GetString("MsgNoCostDisabled_Body", resourceCulture);
        public static string MsgNoPowerEnabled_Body => ResourceManager.GetString("MsgNoPowerEnabled_Body", resourceCulture);
        public static string MsgNoPowerDisabled_Body => ResourceManager.GetString("MsgNoPowerDisabled_Body", resourceCulture);
        public static string MsgBuildHubFirst_Body => ResourceManager.GetString("MsgBuildHubFirst_Body", resourceCulture);
        public static string MsgNoHubFound_Title => ResourceManager.GetString("MsgNoHubFound_Title", resourceCulture);
        public static string MsgResearchUnlocked_Body => ResourceManager.GetString("MsgResearchUnlocked_Body", resourceCulture);
        public static string MsgNoMapManager_Body => ResourceManager.GetString("MsgNoMapManager_Body", resourceCulture);
        public static string MsgNoMapManager_Title => ResourceManager.GetString("MsgNoMapManager_Title", resourceCulture);
        public static string MsgFogOfWarWrongType_Body => ResourceManager.GetString("MsgFogOfWarWrongType_Body", resourceCulture);
        public static string MsgWrongPropertyType_Title => ResourceManager.GetString("MsgWrongPropertyType_Title", resourceCulture);
        public static string MsgFogOfWarUnexpectedCount_Body => ResourceManager.GetString("MsgFogOfWarUnexpectedCount_Body", resourceCulture);
        public static string MsgWarning_Title => ResourceManager.GetString("MsgWarning_Title", resourceCulture);
        public static string PromptRevealMap_Title => ResourceManager.GetString("PromptRevealMap_Title", resourceCulture);
        public static string PromptRevealMap_Caption => ResourceManager.GetString("PromptRevealMap_Caption", resourceCulture);
        public static string PromptRevealMap_Detail => ResourceManager.GetString("PromptRevealMap_Detail", resourceCulture);
        public static string MsgRevealMapRange_Body => ResourceManager.GetString("MsgRevealMapRange_Body", resourceCulture);
        public static string MsgMapDataUncovered_Body => ResourceManager.GetString("MsgMapDataUncovered_Body", resourceCulture);
        public static string PromptDoggoCount_Title => ResourceManager.GetString("PromptDoggoCount_Title", resourceCulture);
        public static string MsgDoggoSpawned_Body => ResourceManager.GetString("MsgDoggoSpawned_Body", resourceCulture);
        public static string MsgDoggoCannotSpawn_Body => ResourceManager.GetString("MsgDoggoCannotSpawn_Body", resourceCulture);
        public static string MsgNoUnlockSubsystemMap_Body => ResourceManager.GetString("MsgNoUnlockSubsystemMap_Body", resourceCulture);
        public static string MsgMapUnlocked_Body => ResourceManager.GetString("MsgMapUnlocked_Body", resourceCulture);
    }
}
