using System;
using System.Collections.Generic;

namespace SatisfactorySaveEditor.Util
{
    /// <summary>
    ///     Satisfactory のクラス名（TOC のクラスパス末尾セグメント、例 "Build_ConveyorBeltMk6_C" /
    ///     "FGFactoryConnectionComponent"）→ 日本語表示名のマッピング。
    ///     ja カルチャのときに <see cref="FriendlyName"/> がこれを引く。未収録のクラスは英語ヒューリスティックへフォールバックする。
    ///     セーブデータは一切変更しない（表示専用）。コンベア／電力／構造／コンポーネント系は確度高、
    ///     一部の生産設備はベストエフォート（公式ローカライズ未取り込みのため）。
    /// </summary>
    public static class FriendlyNameMap
    {
        public static readonly IReadOnlyDictionary<string, string> Ja = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // ---- コンポーネント / サブシステム（内部オブジェクト） ----
            ["FGFactoryConnectionComponent"] = "ファクトリー接続",
            ["FGInventoryComponent"] = "インベントリ",
            ["FGInventoryComponentEquipment"] = "装備インベントリ",
            ["FGInventoryComponentTrash"] = "ゴミ箱インベントリ",
            ["FGPipeConnectionComponent"] = "パイプ接続",
            ["FGPipeConnectionComponentHyper"] = "ハイパーチューブ接続",
            ["FGPipeConnectionFactory"] = "パイプ接続（設備）",
            ["FGPowerConnectionComponent"] = "電力接続",
            ["FGPowerInfoComponent"] = "電力情報",
            ["FGPowerCircuit"] = "電力回路",
            ["FGFactoryLegsComponent"] = "支柱",
            ["FGConveyorChainActor"] = "コンベアチェーン",
            ["FGConveyorChainActor_RepSizeMedium"] = "コンベアチェーン（中）",
            ["FGConveyorChainActor_RepSizeLarge"] = "コンベアチェーン（大）",
            ["FGConveyorChainActor_RepSizeHuge"] = "コンベアチェーン（特大）",
            ["FGRailroadTrackConnectionComponent"] = "線路接続",
            ["FGTrainPlatformConnection"] = "列車プラットフォーム接続",
            ["FGPipeNetwork"] = "パイプネットワーク",
            ["FGBlueprintProxy"] = "ブループリント",
            ["FGDroneStationInfo"] = "ドローンステーション情報",
            ["FGDroneMovementComponent"] = "ドローン移動",
            ["FGRecipeShortcut"] = "レシピショートカット",
            ["FGRecipeManager"] = "レシピマネージャー",
            ["FGRailroadTimeTable"] = "列車時刻表",
            ["FGTrainStationIdentifier"] = "駅識別子",
            ["FGDockingStationIdentifier"] = "ドッキングステーション識別子",
            ["FGPlayerHotbar"] = "ホットバー",
            ["FGHealthComponent"] = "体力",
            ["FGFactoryCustomizationShortcut"] = "カスタマイズショートカット",
            ["FGShoppingListComponent"] = "買い物リスト",
            ["FGVehiclePathNetwork"] = "車両経路ネットワーク",
            ["FGWorldSettings"] = "ワールド設定",
            ["FGFoliageRemovalSubsystem"] = "植生除去サブシステム",
            ["FGLightweightBuildableSubsystem"] = "軽量建築物サブシステム",
            ["FGCentralStorageSubsystem"] = "中央ストレージサブシステム",
            ["FGMapManager"] = "マップマネージャー",
            ["FGPipeSubsystem"] = "パイプサブシステム",
            ["FGResourceSinkSubsystem"] = "資源シンクサブシステム",
            ["FGStatisticsSubsystem"] = "統計サブシステム",
            ["FGScannableSubsystem"] = "スキャンサブシステム",
            ["FGGameRulesSubsystem"] = "ゲームルールサブシステム",

            // ---- 生物（クリーチャー） ----
            ["BP_HogParts_C"] = "ホッグ",
            ["BP_AlphaHogParts_C"] = "アルファホッグ",
            ["BP_CliffHogParts_C"] = "クリフホッグ",
            ["BP_NuclearHogParts_C"] = "ニュークリアホッグ",
            ["BP_StingerParts_C"] = "スティンガー",
            ["BP_AlphaStingerParts_C"] = "アルファスティンガー",
            ["BP_EliteStingerParts_C"] = "エリートスティンガー",
            ["BP_SpitterParts_C"] = "スピッター",
            ["BP_AlphaSpitterParts_C"] = "アルファスピッター",
            ["BP_CrabEggParts_C"] = "クラブの卵",
            ["Char_SpaceGiraffe_C"] = "スペースジラフ",
            ["Char_SpaceRabbit_C"] = "スペースラビット",
            ["Char_Player_C"] = "プレイヤー",

            // ---- ワールドの収集物・自然物 ----
            ["BP_ResourceNode_C"] = "資源ノード",
            ["BP_ResourceNodeGeyser_C"] = "間欠泉",
            ["BP_ResourceDeposit_C"] = "資源の堆積",
            ["BP_FrackingSatellite_C"] = "資源井（衛星）",
            ["BP_FrackingCore_C"] = "資源井コア",
            ["BP_DropPod_C"] = "ドロップポッド",
            ["BP_DestructibleLargeRock_C"] = "大岩",
            ["BP_GasPillar_01_C"] = "ガス柱",
            ["BP_GasPillar_02_C"] = "ガス柱",
            ["BP_GasPillar_03_C"] = "ガス柱",
            ["BP_TapePickup_C"] = "テープ（収集物）",
            ["BP_Ship_C"] = "墜落船",
            ["BP_Crate_C"] = "クレート",
            ["BP_ItemPickup_Spawnable_C"] = "ドロップアイテム",

            // ---- 乗り物・列車・ドローン ----
            ["BP_Train_C"] = "列車",
            ["BP_Locomotive_C"] = "電気機関車",
            ["BP_FreightWagon_C"] = "貨車",
            ["BP_DroneTransport_C"] = "ドローン",
            ["BP_ElevatorCabin_C"] = "エレベーターのかご",

            // ---- 各種サブシステム / マネージャー（BP_） ----
            ["BP_GameMode_C"] = "ゲームモード",
            ["BP_GameState_C"] = "ゲーム状態",
            ["BP_PlayerState_C"] = "プレイヤー状態",
            ["BP_BuildableSubsystem_C"] = "建築物サブシステム",
            ["BP_Sky_Sphere_C"] = "空",
            ["BP_TimeOfDaySubsystem_C"] = "時刻サブシステム",
            ["BP_EventSubsystem_C"] = "イベントサブシステム",
            ["BP_CircuitSubsystem_C"] = "回路サブシステム",
            ["BP_RailroadSubsystem_C"] = "鉄道サブシステム",
            ["BP_VehicleSubsystem_C"] = "車両サブシステム",
            ["BP_BlueprintSusbystem_C"] = "ブループリントサブシステム",
            ["BP_StorySubsystem_C"] = "ストーリーサブシステム",
            ["BP_IconDatabaseSubsystem_C"] = "アイコンDBサブシステム",
            ["BP_SchematicManager_C"] = "設計図マネージャー",
            ["BP_GamePhaseManager_C"] = "ゲームフェーズマネージャー",
            ["BP_ResearchManager_C"] = "研究マネージャー",
            ["BP_TutorialIntroManager_C"] = "チュートリアルマネージャー",
            ["BP_UnlockSubsystem_C"] = "アンロックサブシステム",
            ["BP_ProjectAssembly_C"] = "プロジェクト・アセンブリ",
            ["BP_ResourceScanner_C"] = "資源スキャナー",
            ["BP_BuildGun_C"] = "ビルドガン",

            // ---- 物流：コンベア / リフト / 付属 ----
            ["Build_ConveyorBeltMk1_C"] = "コンベアベルト Mk.1",
            ["Build_ConveyorBeltMk2_C"] = "コンベアベルト Mk.2",
            ["Build_ConveyorBeltMk3_C"] = "コンベアベルト Mk.3",
            ["Build_ConveyorBeltMk4_C"] = "コンベアベルト Mk.4",
            ["Build_ConveyorBeltMk5_C"] = "コンベアベルト Mk.5",
            ["Build_ConveyorBeltMk6_C"] = "コンベアベルト Mk.6",
            ["Build_ConveyorLiftMk1_C"] = "コンベアリフト Mk.1",
            ["Build_ConveyorLiftMk3_C"] = "コンベアリフト Mk.3",
            ["Build_ConveyorLiftMk4_C"] = "コンベアリフト Mk.4",
            ["Build_ConveyorLiftMk5_C"] = "コンベアリフト Mk.5",
            ["Build_ConveyorLiftMk6_C"] = "コンベアリフト Mk.6",
            ["Build_ConveyorAttachmentSplitter_C"] = "分流機",
            ["Build_ConveyorAttachmentSplitterSmart_C"] = "スマート分流機",
            ["Build_ConveyorAttachmentSplitterLift_C"] = "分流機（リフト）",
            ["Build_ConveyorAttachmentMerger_C"] = "合流機",
            ["Build_ConveyorAttachmentMergerLift_C"] = "合流機（リフト）",
            ["Build_ConveyorCeilingAttachment_C"] = "コンベア天井取付",
            ["Build_ConveyorPole_C"] = "コンベアポール",
            ["Build_ConveyorPoleWall_C"] = "コンベアポール（壁）",
            ["Build_ConveyorMonitor_C"] = "コンベアモニター",
            ["Build_ConveyorWallHole_C"] = "コンベア用壁穴",

            // ---- 物流：パイプ / ハイパーチューブ ----
            ["Build_PipelineMK2_C"] = "パイプライン Mk.2",
            ["Build_PipelineMK2_NoIndicator_C"] = "パイプライン Mk.2（表示なし）",
            ["Build_Pipeline_NoIndicator_C"] = "パイプライン Mk.1（表示なし）",
            ["Build_PipelineJunction_Cross_C"] = "パイプライン分岐（十字）",
            ["Build_PipelineFlowIndicator_C"] = "パイプライン流量計",
            ["Build_PipelineSupport_C"] = "パイプライン支柱",
            ["Build_PipelineSupportWall_C"] = "パイプライン支柱（壁）",
            ["Build_PipelineSupportWallHole_C"] = "パイプライン支柱（壁穴）",
            ["Build_PipelinePumpMk2_C"] = "パイプラインポンプ Mk.2",
            ["Build_Valve_C"] = "バルブ",
            ["Build_PipeHyper_C"] = "ハイパーチューブ",
            ["Build_PipeHyperSupport_C"] = "ハイパーチューブ支柱",
            ["Build_PipeHyperStart_C"] = "ハイパーチューブ入口",
            ["Build_HyperTubeWallHole_C"] = "ハイパーチューブ用壁穴",
            ["Build_HypertubeTJunction_C"] = "ハイパーチューブ分岐（T字）",
            ["Build_HyperTubeJunction_C"] = "ハイパーチューブ分岐",

            // ---- 電力 ----
            ["Build_PowerLine_C"] = "送電線",
            ["Build_PowerStorageMk1_C"] = "電力貯蔵庫",
            ["Build_PowerTower_C"] = "パワータワー",
            ["Build_PowerTowerPlatform_C"] = "パワータワー（プラットフォーム）",
            ["Build_PowerSwitch_C"] = "電源スイッチ",
            ["Build_PriorityPowerSwitch_C"] = "優先電源スイッチ",
            ["Build_PowerPoleMk1_C"] = "送電ポール Mk.1",
            ["Build_PowerPoleMk2_C"] = "送電ポール Mk.2",
            ["Build_PowerPoleMk3_C"] = "送電ポール Mk.3",
            ["Build_PowerPoleWall_C"] = "送電ポール（壁） Mk.1",
            ["Build_PowerPoleWall_Mk2_C"] = "送電ポール（壁） Mk.2",
            ["Build_PowerPoleWall_Mk3_C"] = "送電ポール（壁） Mk.3",
            ["Build_PowerPoleWallDouble_C"] = "送電ポール（壁・両面） Mk.1",
            ["Build_PowerPoleWallDouble_Mk2_C"] = "送電ポール（壁・両面） Mk.2",
            ["Build_PowerPoleWallDouble_Mk3_C"] = "送電ポール（壁・両面） Mk.3",
            ["Build_AlienPowerBuilding_C"] = "エイリアン発電増幅器",

            // ---- 発電 ----
            ["Build_GeneratorBiomass_Automated_C"] = "バイオマス発電機",
            ["Build_GeneratorIntegratedBiomass_C"] = "バイオマスバーナー（一体型）",
            ["Build_GeneratorFuel_C"] = "燃料発電機",
            ["Build_GeneratorNuclear_C"] = "原子力発電所",
            ["Build_GeneratorGeoThermal_C"] = "地熱発電機",

            // ---- 生産設備（ベストエフォート） ----
            ["Build_ConstructorMk1_C"] = "製作機",
            ["Build_AssemblerMk1_C"] = "組立機",
            ["Build_ManufacturerMk1_C"] = "製造機",
            ["Build_SmelterMk1_C"] = "製錬炉",
            ["Build_FoundryMk1_C"] = "鋳造炉",
            ["Build_OilRefinery_C"] = "精製所",
            ["Build_Blender_C"] = "ブレンダー",
            ["Build_Converter_C"] = "コンバーター",
            ["Build_HadronCollider_C"] = "粒子加速器",
            ["Build_QuantumEncoder_C"] = "量子エンコーダー",
            ["Build_Packager_C"] = "梱包機",

            // ---- 採取 ----
            ["Build_MinerMk3_C"] = "採掘機 Mk.3",
            ["Build_WaterPump_C"] = "取水ポンプ",
            ["Build_OilPump_C"] = "石油採掘機",
            ["Build_FrackingExtractor_C"] = "資源井採掘機",
            ["Build_FrackingSmasher_C"] = "資源井加圧機",

            // ---- 貯蔵 ----
            ["Build_StorageContainerMk1_C"] = "貯蔵庫",
            ["Build_StorageContainerMk2_C"] = "大型貯蔵庫",
            ["Build_StorageIntegrated_C"] = "貯蔵庫（一体型）",
            ["Build_CentralStorage_C"] = "次元デポ",
            ["Build_IndustrialTank_C"] = "産業用貯蔵タンク",
            ["Build_PipeStorageTank_C"] = "流体貯蔵庫",

            // ---- 鉄道 ----
            ["Build_RailroadTrack_C"] = "線路",
            ["Build_RailroadTrackIntegrated_C"] = "線路（一体型）",
            ["Build_RailroadBlockSignal_C"] = "閉塞信号機",
            ["Build_RailroadPathSignal_C"] = "経路信号機",
            ["Build_RailroadSwitchControl_C"] = "分岐器コントロール",
            ["Build_TrainStation_C"] = "鉄道駅",
            ["Build_TrainDockingStation_C"] = "貨物積込ステーション",
            ["Build_TrainDockingStationLiquid_C"] = "貨物積込ステーション（液体）",
            ["Build_TrainPlatformEmpty_C"] = "空の列車プラットフォーム",
            ["Build_TrainPlatformEmpty_02_C"] = "空の列車プラットフォーム",

            // ---- 車両・ドローン・物流ステーション ----
            ["Build_DroneStation_C"] = "ドローンポート",
            ["Build_TruckStation_C"] = "トラックステーション",
            ["Build_VehiclePathNode_DockingStation_C"] = "車両経路ノード（積込）",

            // ---- ハブ・MAM・特殊 ----
            ["Build_TradingPost_C"] = "HUB",
            ["Build_HubTerminal_C"] = "HUB端末",
            ["Build_WorkBench_C"] = "作業台",
            ["Build_WorkBenchIntegrated_C"] = "作業台（一体型）",
            ["Build_Workshop_C"] = "装備工房",
            ["Build_Mam_C"] = "MAM",
            ["Build_SpaceElevator_C"] = "スペースエレベーター",
            ["Build_ResourceSink_C"] = "AWESOMEシンク",
            ["Build_ResourceSinkShop_C"] = "AWESOMEショップ",
            ["Build_Portal_C"] = "ポータル",
            ["Build_PortalSatellite_C"] = "サテライトポータル",
            ["Build_RadarTower_C"] = "レーダータワー",

            // ---- 照明・看板 ----
            ["Build_CeilingLight_C"] = "天井ライト",
            ["Build_StreetLight_C"] = "街灯",
            ["Build_FloodlightWall_C"] = "投光器（壁）",
            ["Build_FloodlightPole_C"] = "投光器（ポール）",
            ["Build_LightsControlPanel_C"] = "照明コントロールパネル",
            ["Build_SignPole_C"] = "看板ポール",
            ["Build_StandaloneWidgetSign_Small_C"] = "看板（小）",
            ["Build_StandaloneWidgetSign_SmallVeryWide_C"] = "看板（横長・小）",
            ["Build_StandaloneWidgetSign_Medium_C"] = "看板（中）",
            ["Build_StandaloneWidgetSign_Large_C"] = "看板（大）",
            ["Build_StandaloneWidgetSign_Huge_C"] = "看板（特大）",
            ["Build_StandaloneWidgetSign_Square_C"] = "看板（正方形）",
            ["Build_StandaloneWidgetSign_Square_Small_C"] = "看板（正方形・小）",
            ["Build_StandaloneWidgetSign_Square_Tiny_C"] = "看板（正方形・極小）",
            ["Build_StandaloneWidgetSign_Portrait_C"] = "看板（縦）",

            // ---- 構造：基礎 / 梁 / 壁 / 通路 ----
            ["Build_Beam_Connector_C"] = "ビーム接続部",
            ["Build_Beam_Support_C"] = "ビーム支柱",
            ["Build_FoundationPassthrough_Lift_C"] = "貫通フレーム（リフト）",
            ["Build_FoundationPassthrough_Pipe_C"] = "貫通フレーム（パイプ）",
            ["Build_Ladder_C"] = "はしご",
            ["Build_Gate_Automated_8x4_C"] = "自動ゲート",
            ["Build_Elevator_C"] = "エレベーター",
            ["Build_ElevatorFloorStop_C"] = "エレベーター停止階",
            ["Build_Wall_Door_8x4_01_C"] = "壁（ドア）",
            ["Build_Wall_Door_8x4_03_C"] = "壁（ドア）",
            ["Build_Wall_Concrete_SDoor_8x4_C"] = "コンクリート壁（片開きドア）",
            ["Build_Wall_Concrete_CDoor_8x4_C"] = "コンクリート壁（両開きドア）",
            ["Build_Wall_Conveyor_8x4_01_C"] = "壁（コンベア穴）",
            ["Build_Wall_Conveyor_8x4_02_C"] = "壁（コンベア穴）",
            ["Build_Wall_Conveyor_8x4_03_C"] = "壁（コンベア穴）",
            ["Build_Wall_Conveyor_8x4_02_Steel_C"] = "鋼鉄壁（コンベア穴）",
            ["Build_Wall_Conveyor_8x4_03_Steel_C"] = "鋼鉄壁（コンベア穴）",
            ["Build_Wall_Concrete_8x4_ConveyorHole_01_C"] = "コンクリート壁（コンベア穴）",
            ["Build_Wall_Concrete_8x4_ConveyorHole_02_C"] = "コンクリート壁（コンベア穴）",
            ["Build_Wall_Concrete_8x4_ConveyorHole_03_C"] = "コンクリート壁（コンベア穴）",

            // ---- 装備（Equip_） ----
            ["Equip_ResourceMiner_C"] = "携帯採掘機",
            ["Equip_ObjectScanner_C"] = "オブジェクトスキャナー",
            ["Equip_Rifle_C"] = "ライフル",
            ["Equip_RebarGun_Projectile_C"] = "鉄筋ガン",
            ["Equip_MedKit_C"] = "医療用インヘラー",
            ["Equip_Zipline_C"] = "ジップライン",
            ["Equip_JumpingStilts_C"] = "ブレードランナー",
            ["Equip_GasMask_C"] = "ガスマスク",
            ["Equip_HazmatSuit_C"] = "防護服",
            ["Equip_HoverPack_C"] = "ホバーパック",
            ["Equip_CupGold_C"] = "金のFICSITカップ",

            // ---- その他・イースターエッグ ----
            ["Build_XmassTree_C"] = "クリスマスツリー",
            ["BUILD_Potty_mk1_C"] = "FICSITトイレ",
        };
    }
}
